apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.fullname" . }}-config
  labels:
    {{- include "hive-metastore.commonLabels" . | nindent 4 }}
  annotations:
    "meta.helm.sh/release-name": "{{ include "hive-metastore.fullname" . }}"
    "meta.helm.sh/release-namespace": "{{ .Release.Namespace }}"
type: Opaque
data:
  hive-site.xml: |
    {{ include "metastore.hiveSite" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.fullname" . }}-snowflake-config
  labels:
    {{- include "hive-metastore.commonLabels" . | nindent 4 }}
type: Opaque
data:
  snowflake-config.xml: |
    {{ include "metastore.snowflakeConnector" . | b64enc }}
