apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  labels:
    {{- include "hive-metastore.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.fullname" . }}-external
  annotations: {}
  labels:
    {{- include "hive-metastore.commonLabels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9083
      protocol: TCP
      nodePort: 30021
      name: http
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
